# Generated by Django 4.0 on 2022-10-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JsonResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('slackUsername', models.CharField(blank=True, max_length=200, null=True)),
                ('backend', models.BooleanField(default=False)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
